alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: byteme-ai
    cors: {}
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: byteme-ai
region: blr
services:
- dockerfile_path: /Dockerfile
  envs:
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: byte-me-instance-1.c1yc40cskc5f.ca-central-1.rds.amazonaws.com
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: "5432"
  - key: DB_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: postgres
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: i!m%GpJ;x$8$vx&
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: byteme-ai
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: your-super-secret-jwt-key-change-in-production
  - key: JWT_EXPIRES_IN
    scope: RUN_AND_BUILD_TIME
    value: 7d
  - key: VECHAIN_NETWORK
    scope: RUN_AND_BUILD_TIME
    value: testnet
  - key: VECHAIN_NODE_URL
    scope: RUN_AND_BUILD_TIME
    value: https://testnet.vechain.org
  - key: B3TR_CONTRACT_ADDRESS
    scope: RUN_AND_BUILD_TIME
    value: "0x0000000000000000000000000000000000000000"
  - key: ADMIN_PRIVATE_KEY
    scope: RUN_AND_BUILD_TIME
    value: your-admin-private-key
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: development
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "3000"
  - key: ALLOWED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: http://localhost:3000,http://localhost:3001
  - key: SMTP_HOST
    scope: RUN_AND_BUILD_TIME
    value: smtp.gmail.com
  - key: SMTP_PORT
    scope: RUN_AND_BUILD_TIME
    value: "587"
  - key: SMTP_USER
    scope: RUN_AND_BUILD_TIME
    value: your-email@gmail.com
  - key: SMTP_PASS
    scope: RUN_AND_BUILD_TIME
    value: your-app-password
  - key: MAX_FILE_SIZE
    scope: RUN_AND_BUILD_TIME
    value: "10485760"
  - key: UPLOAD_PATH
    scope: RUN_AND_BUILD_TIME
    value: ./uploads
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: 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
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
    value: AKIAWVDQTXX3IX5YGAMY
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    value: 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
  - key: EMAIL_PASS
    scope: RUN_AND_BUILD_TIME
    value: gort axak ndzx peej
  github:
    branch: main
    deploy_on_push: true
    repo: arpanalchemy/byteme-ai
  health_check:
    http_path: /healthcheck
    initial_delay_seconds: 120
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  http_port: 3000
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: byteme-ai
  run_command: npm run start:dev
